"""Shared append-only hash chain for platform event tables."""

import re
import sqlite3

from alphasieve.util import canonical_json, sha256_hex, utcnow_iso

GENESIS_HASH = "0" * 64


def _identifier(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", value):
        raise ValueError(f"invalid SQL identifier: {value!r}")
    return f'"{value}"'


def append_chained(conn: sqlite3.Connection, table: str, row: dict,
                   hashed_cols: tuple[str, ...]) -> dict:
    name = _identifier(table)
    data = dict(row)
    if any(col not in data for col in hashed_cols):
        raise ValueError("hashed column missing from row")
    if any(col in data for col in ("seq", "created_at", "prev_hash", "row_hash")):
        raise ValueError("chain metadata must be generated by append_chained")
    columns = tuple(data)
    quoted = ",".join(_identifier(col) for col in (*columns, "created_at", "prev_hash", "row_hash"))
    slots = ",".join("?" for _ in range(len(columns) + 3))
    conn.execute("BEGIN IMMEDIATE")
    try:
        prior = conn.execute(f"SELECT row_hash FROM {name} ORDER BY seq DESC LIMIT 1").fetchone()
        prev = prior[0] if prior else GENESIS_HASH
        data.update(created_at=utcnow_iso(), prev_hash=prev,
                    row_hash=sha256_hex(prev + canonical_json({col: data[col] for col in hashed_cols})))
        cursor = conn.execute(f"INSERT INTO {name} ({quoted}) VALUES ({slots})",
                              tuple(data[col] for col in (*columns, "created_at", "prev_hash", "row_hash")))
        data["seq"] = cursor.lastrowid
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    return data


def verify_chain(conn: sqlite3.Connection, table: str, hashed_cols: tuple[str, ...]) -> dict:
    name = _identifier(table)
    for col in hashed_cols:
        _identifier(col)
    errors = []
    prev = GENESIS_HASH
    count = 0
    for record in conn.execute(f"SELECT * FROM {name} ORDER BY seq"):
        row = dict(record)
        count += 1
        seq = row["seq"]
        if row["prev_hash"] != prev:
            errors.append({"seq": seq, "error": "prev_hash mismatch"})
        expected = sha256_hex(row["prev_hash"] + canonical_json({col: row[col] for col in hashed_cols}))
        if row["row_hash"] != expected:
            errors.append({"seq": seq, "error": "row_hash mismatch"})
        prev = row["row_hash"]
    return {"ok": not errors, "rows": count, "errors": errors}
